spring:
  application:
    name: form-based
  datasource:
    url: jdbc:mysql://localhost:3306/bblog
    username: root
    password: wjd747
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create